### ISSUE TITLE
How to install `flexBCF`?

### ISSUE THREAD

**Issue by Gattocrucco** [skdeshpande91/flexBCF#1]
Hi, I wanted to give a look to `flexBCF`, but it is not obvious to me how to install it. I'm new to R, I mostly use Python.

I tried

```R
devtools::install_github("skdeshpande91/flexBCF")
```

but it fails with

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`skdeshpande91`) and repo name (`flexBCF`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

The internet connection, the spelling, and the public access are O-K, so my current guess is that for this to work the repository must be set up in a certain way.

Could you help me install your software?

**Comment by skdeshpande91** [comment]
The package source code is located in the `flexBCF` subdirectory, so you will need to use
```
devtools::install_github(repo = "skdeshpande91/flexBCF", subdir = "flexBCF")
```
